apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-ingest-rtmp.fullname" . }}-config
  labels:
    {{- include "wasp-ingest-rtmp.labels" . | nindent 4 }}
data:
  logLevel: {{ .Values.config.logLevel }}
  kafkaBrokers: {{ include "wasp-ingest-rtmp.kafka.brokers" . }}
  kafkaTopic: {{ .Values.config.kafkaTopic }}